# Generated by Django 5.2.6 on 2025-12-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
