# Generated by Django 5.2.6 on 2025-12-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(upload_to='certificates/'),
        ),
    ]
