# Generated by Django 5.2.6 on 2025-12-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_certificate_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
