# Generated by Django 6.0.1 on 2026-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certificate1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
