# Generated by Django 6.0.1 on 2026-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_certificate3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.FileField(upload_to='certificates/')),
            ],
        ),
    ]
