# Generated by Django 6.0.1 on 2026-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_certificate4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate1',
        ),
        migrations.DeleteModel(
            name='Certificate3',
        ),
        migrations.DeleteModel(
            name='Certificate4',
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Sertifikat raqami'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.FileField(upload_to='certificates/', verbose_name='Sertifikat fayli'),
        ),
    ]
