# Generated by Django 6.0.1 on 2026-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_certificate1_delete_certificate3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='media/')),
            ],
        ),
    ]
